'use client';

import CompassLogo from '@/components/CompassLogo';

export default function Footer() {
  return (
    <footer style={{
      background: 'linear-gradient(135deg, #2D0A00, #5C1010)',
      color: 'rgba(255,255,255,0.7)',
      padding: '40px 2rem 20px',
      marginTop: '60px',
      fontFamily: "'Nunito', sans-serif",
      fontSize: '0.85rem',
    }}>
      <div style={{ maxWidth: '1100px', margin: '0 auto' }}>
        <div className="footer-grid" style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr', gap: '40px', marginBottom: '32px' }}>

          {/* Brand */}
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px' }}>
              <CompassLogo size={42} />
              <div>
                <div style={{ fontFamily: "'Playfair Display', serif", fontSize: '1.3rem', color: '#FFD700', lineHeight: 1.2 }}>Roamai</div>
                <div style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.4)', fontStyle: 'italic' }}>రోమేయ్ — roam around freely</div>
              </div>
            </div>
            <p style={{ lineHeight: 1.7, color: 'rgba(255,255,255,0.6)' }}>
              India&apos;s AI-powered domestic travel companion. Plan trips, track budgets, get personalised itineraries and explore the best of Incredible India — from the Himalayas to the backwaters.
            </p>
            <div style={{ marginTop: '12px', color: 'rgba(255,255,255,0.4)', fontSize: '0.78rem' }}>
              🇮🇳 Made with ❤️ for Indian Travellers
            </div>
          </div>

          {/* Popular Destinations */}
          <div>
            <div style={{ fontWeight: 700, color: '#FFD700', marginBottom: '12px', fontFamily: "'Baloo 2', sans-serif" }}>
              Popular Destinations
            </div>
            <div style={{ lineHeight: 2, color: 'rgba(255,255,255,0.6)' }}>
              Rajasthan • Kerala<br />
              Goa • Himachal Pradesh<br />
              Ladakh • Varanasi<br />
              Andaman • Coorg<br />
              Rishikesh • Mysuru
            </div>
          </div>

          {/* Travel Categories */}
          <div>
            <div style={{ fontWeight: 700, color: '#FFD700', marginBottom: '12px', fontFamily: "'Baloo 2', sans-serif" }}>
              Travel Categories
            </div>
            <div style={{ lineHeight: 2, color: 'rgba(255,255,255,0.6)' }}>
              👩 Women Solo Travel<br />
              🧳 Single Travel<br />
              👨‍👩‍👧 Family Trips<br />
              👴 Senior Travel<br />
              🎒 Budget Travel<br />
              🧗 Adventure Travel<br />
              🙏 Spiritual Tours
            </div>
          </div>
        </div>

        {/* AI Disclaimer */}
        <div style={{
          background: 'rgba(255,255,255,0.05)',
          border: '1px solid rgba(255,255,255,0.1)',
          borderRadius: '10px',
          padding: '14px 18px',
          marginBottom: '20px',
          fontSize: '0.78rem',
          lineHeight: 1.7,
          color: 'rgba(255,255,255,0.5)',
        }}>
          <strong style={{ color: 'rgba(255,200,100,0.8)' }}>⚠️ AI-Generated Content Disclaimer:</strong> All itineraries, travel tips, budget estimates, packing suggestions and recommendations on Roamai are generated by artificial intelligence (Claude by Anthropic) and are for informational and planning purposes only. They may contain inaccuracies or outdated information. Always verify details — including prices, timings, safety conditions, visa requirements and local regulations — through official sources and authorised travel agents before making any bookings or decisions. Roamai accepts no liability for losses arising from reliance on AI-generated content.
        </div>

        {/* Bottom bar */}
        <div style={{
          borderTop: '1px solid rgba(255,255,255,0.1)',
          paddingTop: '16px',
          display: 'flex',
          justifyContent: 'space-between',
          flexWrap: 'wrap',
          gap: '10px',
        }}>
          <span>© {new Date().getFullYear()} Roamai – Your AI Travel Companion for India. Free to use.</span>
          <span style={{ color: 'rgba(255,255,255,0.4)' }}>AI-powered itineraries • Budget tracker • Packing checklist • Seasonal guides</span>
        </div>
      </div>
    </footer>
  );
}
