import type { ChecklistData } from '@/types';

export const defaultChecklist: ChecklistData = {
  '📄 Documents': [
    'Aadhar Card / PAN Card',
    'Passport (if needed)',
    'Train/Flight e-tickets',
    'Hotel booking confirmation',
    'Travel insurance',
    'Emergency contacts list',
    'Driving licence (if self-drive)',
  ],
  '👗 Clothing': [
    'T-shirts / Tops',
    'Bottoms (pants/skirts)',
    'Light jacket / Shawl',
    'Comfortable walking shoes',
    'Slippers / Sandals',
    'Formal outfit (if needed)',
    'Innerwear & socks (extra)',
    'Rain jacket / Umbrella',
  ],
  '💊 Health & Safety': [
    'Prescription medicines',
    'First-aid kit',
    'Hand sanitiser',
    'Face masks',
    'Sunscreen SPF 50+',
    'Insect repellent',
    'ORS sachets',
    'Motion sickness tablets',
    'Pain killers',
    'Thermometer',
  ],
  '🔌 Electronics': [
    'Phone charger',
    'Power bank (10,000 mAh+)',
    'Earphones / Headphones',
    'Camera',
    'Universal adapter',
    'Laptop / Tablet',
    'Memory cards',
    'Selfie stick',
  ],
  '🧴 Toiletries': [
    'Toothbrush & toothpaste',
    'Shampoo & conditioner',
    'Body wash / Soap',
    'Moisturiser',
    'Deodorant',
    'Hair brush / comb',
    'Sanitary products',
  ],
  '🎒 Essentials': [
    'Backpack / Day bag',
    'Water bottle (1L+)',
    'Snacks for travel',
    'Padlock for luggage',
    'Earplugs',
    'Eye mask',
    'Travel pillow',
    'Notebook & pen',
    'Cash (₹ small denominations)',
    'Downloaded offline maps',
  ],
};
