export type Region = 'north' | 'south' | 'east' | 'west' | 'central' | 'northeast';
export type Vibe = 'heritage' | 'nature' | 'adventure' | 'spiritual' | 'wildlife' | 'beach' | 'hill' | 'cultural' | 'romantic';

export interface Circuit {
  id: string;
  name: string;
  tagline: string;
  region: Region;
  vibes: Vibe[];
  cities: string[];          // in order
  anchorCity: string;        // main "from" city / entry point
  daysMin: number;
  daysMax: number;
  highlights: string[];      // 3-4 bullet highlights
  bestMonths: string[];
  difficulty: 'easy' | 'moderate' | 'challenging';
  icon: string;
  coverEmoji: string;
  popular: boolean;
}

const CIRCUITS: Circuit[] = [

  // ── NORTH INDIA ──────────────────────────────────────────────────────────
  {
    id: 'golden-triangle',
    name: 'Golden Triangle',
    tagline: 'India\'s most iconic heritage loop',
    region: 'north',
    vibes: ['heritage', 'cultural'],
    cities: ['Delhi', 'Agra', 'Jaipur'],
    anchorCity: 'Delhi',
    daysMin: 5,
    daysMax: 8,
    highlights: ['Taj Mahal at sunrise', 'Amber Fort elephant ride', 'Old Delhi street food', 'Fatehpur Sikri ruins'],
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March'],
    difficulty: 'easy',
    icon: '🔺',
    coverEmoji: '🕌',
    popular: true,
  },
  {
    id: 'rajasthan-heritage',
    name: 'Rajasthan Heritage Circuit',
    tagline: 'Palaces, forts & sand dunes',
    region: 'west',
    vibes: ['heritage', 'cultural', 'adventure'],
    cities: ['Jaipur', 'Jodhpur', 'Jaisalmer', 'Udaipur'],
    anchorCity: 'Jaipur',
    daysMin: 10,
    daysMax: 14,
    highlights: ['Mehrangarh Fort at dusk', 'Jaisalmer desert camp', 'Lake Pichola boat ride', 'Havelis of Shekhawati'],
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    difficulty: 'easy',
    icon: '🏰',
    coverEmoji: '🐪',
    popular: true,
  },
  {
    id: 'rajasthan-quick',
    name: 'Rajasthan Quick Loop',
    tagline: 'Best of Rajasthan in a week',
    region: 'west',
    vibes: ['heritage', 'cultural'],
    cities: ['Jaipur', 'Pushkar', 'Jodhpur'],
    anchorCity: 'Jaipur',
    daysMin: 6,
    daysMax: 8,
    highlights: ['Pink City bazaars', 'Pushkar camel fair & ghats', 'Blue City rooftop views', 'Mehrangarh Fort'],
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March'],
    difficulty: 'easy',
    icon: '🏯',
    coverEmoji: '🌅',
    popular: false,
  },
  {
    id: 'himalayan-loop',
    name: 'Himalayan Adventure Loop',
    tagline: 'Snow peaks, valleys & monasteries',
    region: 'north',
    vibes: ['adventure', 'hill', 'nature'],
    cities: ['Shimla', 'Manali', 'Spiti Valley', 'Dharamshala'],
    anchorCity: 'Chandigarh',
    daysMin: 12,
    daysMax: 16,
    highlights: ['Rohtang Pass snow drive', 'Spiti Valley monasteries', 'McLeod Ganj Tibetan culture', 'Solang Valley activities'],
    bestMonths: ['May', 'June', 'September', 'October'],
    difficulty: 'challenging',
    icon: '🏔️',
    coverEmoji: '❄️',
    popular: true,
  },
  {
    id: 'shimla-manali',
    name: 'Shimla–Manali Escape',
    tagline: 'Classic Himachal hill retreat',
    region: 'north',
    vibes: ['hill', 'adventure', 'romantic'],
    cities: ['Shimla', 'Kufri', 'Manali', 'Kasol'],
    anchorCity: 'Chandigarh',
    daysMin: 7,
    daysMax: 10,
    highlights: ['Mall Road Shimla', 'Old Manali cafes', 'Kasol riverside camping', 'Rohtang snow views'],
    bestMonths: ['April', 'May', 'June', 'October', 'November'],
    difficulty: 'moderate',
    icon: '🌨️',
    coverEmoji: '🏔️',
    popular: true,
  },
  {
    id: 'char-dham',
    name: 'Char Dham Yatra',
    tagline: 'The sacred four-shrine pilgrimage',
    region: 'north',
    vibes: ['spiritual'],
    cities: ['Haridwar', 'Yamunotri', 'Gangotri', 'Kedarnath', 'Badrinath'],
    anchorCity: 'Haridwar',
    daysMin: 11,
    daysMax: 14,
    highlights: ['Ganga Aarti at Haridwar', 'Kedarnath trek', 'Mana village (last Indian village)', 'Gangotri glacier views'],
    bestMonths: ['May', 'June', 'September', 'October'],
    difficulty: 'challenging',
    icon: '🙏',
    coverEmoji: '⛰️',
    popular: true,
  },
  {
    id: 'uttarakhand-nature',
    name: 'Uttarakhand Nature Trail',
    tagline: 'Jim Corbett, Rishikesh & Nainital',
    region: 'north',
    vibes: ['wildlife', 'nature', 'adventure', 'spiritual'],
    cities: ['Rishikesh', 'Jim Corbett', 'Nainital', 'Munsiyari'],
    anchorCity: 'Delhi',
    daysMin: 8,
    daysMax: 11,
    highlights: ['White-water rafting in Rishikesh', 'Tiger safari at Corbett', 'Naini Lake boating', 'Panchachuli peak views'],
    bestMonths: ['February', 'March', 'April', 'October', 'November'],
    difficulty: 'moderate',
    icon: '🌿',
    coverEmoji: '🐯',
    popular: false,
  },
  {
    id: 'ladakh-leh',
    name: 'Ladakh & Leh',
    tagline: 'Land of high passes and still lakes',
    region: 'north',
    vibes: ['adventure', 'nature', 'spiritual'],
    cities: ['Leh', 'Pangong Lake', 'Nubra Valley', 'Tso Moriri'],
    anchorCity: 'Leh',
    daysMin: 8,
    daysMax: 12,
    highlights: ['Pangong Lake colour shifts', 'Nubra Valley sand dunes', 'Khardung La pass', 'Thiksey Monastery'],
    bestMonths: ['June', 'July', 'August', 'September'],
    difficulty: 'challenging',
    icon: '🏕️',
    coverEmoji: '🌌',
    popular: true,
  },

  // ── SOUTH INDIA ──────────────────────────────────────────────────────────
  {
    id: 'kerala-complete',
    name: 'Kerala Complete',
    tagline: 'God\'s own country — top to toe',
    region: 'south',
    vibes: ['nature', 'beach', 'wildlife', 'romantic'],
    cities: ['Kochi', 'Munnar', 'Thekkady', 'Alleppey', 'Kovalam'],
    anchorCity: 'Kochi',
    daysMin: 9,
    daysMax: 12,
    highlights: ['Alleppey houseboat stay', 'Munnar tea estates', 'Thekkady elephant safari', 'Kovalam lighthouse beach'],
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March'],
    difficulty: 'easy',
    icon: '🌴',
    coverEmoji: '🚢',
    popular: true,
  },
  {
    id: 'kerala-backwaters',
    name: 'Kerala Backwaters',
    tagline: 'Lazy canals, houseboats & spice farms',
    region: 'south',
    vibes: ['nature', 'romantic', 'beach'],
    cities: ['Kochi', 'Alleppey', 'Kumarakom', 'Varkala'],
    anchorCity: 'Kochi',
    daysMin: 6,
    daysMax: 8,
    highlights: ['Kettuvallam houseboat overnight', 'Kochi Fort & spice market', 'Varkala cliffside beach', 'Kumarakom bird sanctuary'],
    bestMonths: ['November', 'December', 'January', 'February', 'March'],
    difficulty: 'easy',
    icon: '🛶',
    coverEmoji: '🌊',
    popular: true,
  },
  {
    id: 'tamil-heritage',
    name: 'Tamil Nadu Temple Trail',
    tagline: 'Dravidian architecture at its finest',
    region: 'south',
    vibes: ['heritage', 'spiritual', 'cultural'],
    cities: ['Chennai', 'Mahabalipuram', 'Pondicherry', 'Thanjavur', 'Madurai'],
    anchorCity: 'Chennai',
    daysMin: 8,
    daysMax: 11,
    highlights: ['Shore Temple at Mahabalipuram', 'French Quarter Pondicherry', 'Brihadeeswarar Temple Thanjavur', 'Meenakshi Amman Temple'],
    bestMonths: ['November', 'December', 'January', 'February', 'March'],
    difficulty: 'easy',
    icon: '🛕',
    coverEmoji: '🏛️',
    popular: false,
  },
  {
    id: 'south-india-grand',
    name: 'South India Grand Tour',
    tagline: 'Temples, beaches, hills & backwaters',
    region: 'south',
    vibes: ['heritage', 'beach', 'nature', 'cultural'],
    cities: ['Bengaluru', 'Mysuru', 'Ooty', 'Kochi', 'Alleppey', 'Munnar'],
    anchorCity: 'Bengaluru',
    daysMin: 12,
    daysMax: 16,
    highlights: ['Mysore Palace sound & light show', 'Ooty Nilgiri train ride', 'Alleppey houseboat', 'Munnar tea walks'],
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    difficulty: 'easy',
    icon: '🌏',
    coverEmoji: '🌺',
    popular: false,
  },
  {
    id: 'karnataka-heritage',
    name: 'Karnataka Heritage',
    tagline: 'Hampi ruins, Mysore palace & Coorg',
    region: 'south',
    vibes: ['heritage', 'nature', 'adventure'],
    cities: ['Bengaluru', 'Hampi', 'Badami', 'Mysuru', 'Coorg'],
    anchorCity: 'Bengaluru',
    daysMin: 9,
    daysMax: 12,
    highlights: ['Hampi boulder landscape at sunset', 'Badami cave temples', 'Mysore Dasara festival', 'Coorg coffee estate walks'],
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March'],
    difficulty: 'moderate',
    icon: '🏚️',
    coverEmoji: '🌄',
    popular: false,
  },

  // ── EAST INDIA ───────────────────────────────────────────────────────────
  {
    id: 'northeast-explorer',
    name: 'Northeast Explorer',
    tagline: 'Untouched tribes, waterfalls & wildlife',
    region: 'northeast',
    vibes: ['wildlife', 'nature', 'cultural', 'adventure'],
    cities: ['Guwahati', 'Kaziranga', 'Shillong', 'Cherrapunji', 'Majuli'],
    anchorCity: 'Guwahati',
    daysMin: 9,
    daysMax: 12,
    highlights: ['One-horned rhino safari at Kaziranga', 'Living root bridges at Cherrapunji', 'Majuli island river culture', 'Shillong Scottish-style hill town'],
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March'],
    difficulty: 'moderate',
    icon: '🌿',
    coverEmoji: '🦏',
    popular: false,
  },
  {
    id: 'sikkim-darjeeling',
    name: 'Sikkim & Darjeeling',
    tagline: 'Tea gardens, Kanchenjunga views & monasteries',
    region: 'northeast',
    vibes: ['hill', 'nature', 'spiritual', 'romantic'],
    cities: ['Darjeeling', 'Gangtok', 'Pelling', 'Lachung'],
    anchorCity: 'Bagdogra',
    daysMin: 8,
    daysMax: 11,
    highlights: ['Tiger Hill sunrise over Kanchenjunga', 'Rumtek Monastery', 'Toy train Darjeeling', 'Yumthang Valley flowers'],
    bestMonths: ['March', 'April', 'May', 'October', 'November'],
    difficulty: 'moderate',
    icon: '🍵',
    coverEmoji: '🏔️',
    popular: true,
  },
  {
    id: 'odisha-temples',
    name: 'Odisha Spiritual & Tribal',
    tagline: 'Sun Temple, Jagannath & tribal heartland',
    region: 'east',
    vibes: ['spiritual', 'heritage', 'cultural'],
    cities: ['Bhubaneswar', 'Puri', 'Konark', 'Chilika'],
    anchorCity: 'Bhubaneswar',
    daysMin: 5,
    daysMax: 7,
    highlights: ['Konark Sun Temple', 'Puri Jagannath Rath Yatra', 'Chilika Lake flamingos', 'Lingaraj Temple complex'],
    bestMonths: ['October', 'November', 'December', 'January', 'February'],
    difficulty: 'easy',
    icon: '☀️',
    coverEmoji: '🛕',
    popular: false,
  },

  // ── WEST INDIA ───────────────────────────────────────────────────────────
  {
    id: 'goa-konkan',
    name: 'Goa & Konkan Coast',
    tagline: 'Beach clubs, forts & coastal villages',
    region: 'west',
    vibes: ['beach', 'nature', 'romantic', 'adventure'],
    cities: ['Panaji', 'North Goa', 'South Goa', 'Tarkarli', 'Ratnagiri'],
    anchorCity: 'Goa',
    daysMin: 6,
    daysMax: 9,
    highlights: ['Baga & Anjuna nightlife', 'Dudhsagar waterfall', 'Tarkarli scuba diving', 'Sindhudurg sea fort'],
    bestMonths: ['November', 'December', 'January', 'February', 'March'],
    difficulty: 'easy',
    icon: '🏖️',
    coverEmoji: '🌊',
    popular: true,
  },
  {
    id: 'gujarat-heritage',
    name: 'Gujarat Heritage & Rann',
    tagline: 'White desert, lions & step-wells',
    region: 'west',
    vibes: ['heritage', 'wildlife', 'cultural', 'nature'],
    cities: ['Ahmedabad', 'Rann of Kutch', 'Gir Forest', 'Dwaraka', 'Somnath'],
    anchorCity: 'Ahmedabad',
    daysMin: 8,
    daysMax: 11,
    highlights: ['Rann Utsav white desert festival', 'Asiatic lions at Gir', 'Rani ki Vav step-well', 'Dwaraka temple at sunset'],
    bestMonths: ['November', 'December', 'January', 'February'],
    difficulty: 'moderate',
    icon: '🦁',
    coverEmoji: '🏜️',
    popular: false,
  },
  {
    id: 'maharashtra-mix',
    name: 'Maharashtra Mix',
    tagline: 'Caves, ghats, hill stations & beaches',
    region: 'west',
    vibes: ['heritage', 'nature', 'adventure', 'beach'],
    cities: ['Mumbai', 'Pune', 'Lonavala', 'Aurangabad', 'Ajanta & Ellora'],
    anchorCity: 'Mumbai',
    daysMin: 8,
    daysMax: 11,
    highlights: ['Ajanta cave paintings', 'Ellora rock-cut temples', 'Lonavala monsoon ghats', 'Gateway of India Mumbai'],
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March'],
    difficulty: 'easy',
    icon: '🌁',
    coverEmoji: '🏛️',
    popular: false,
  },

  // ── CENTRAL INDIA ────────────────────────────────────────────────────────
  {
    id: 'madhya-pradesh-wildlife',
    name: 'Madhya Pradesh Wildlife',
    tagline: 'Tiger country — Bandhavgarh & Kanha',
    region: 'central',
    vibes: ['wildlife', 'nature', 'adventure'],
    cities: ['Bhopal', 'Bandhavgarh', 'Kanha', 'Pench'],
    anchorCity: 'Bhopal',
    daysMin: 7,
    daysMax: 10,
    highlights: ['Bengal tiger spotting at Bandhavgarh', 'Kanha meadow leopard sightings', 'Jungle walks with naturalists', 'Satpura plateau landscapes'],
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March', 'April'],
    difficulty: 'moderate',
    icon: '🐅',
    coverEmoji: '🌳',
    popular: true,
  },
  {
    id: 'khajuraho-varanasi',
    name: 'Khajuraho & Varanasi',
    tagline: 'Temple sculptures & Ganga ghats',
    region: 'central',
    vibes: ['heritage', 'spiritual', 'cultural'],
    cities: ['Khajuraho', 'Prayagraj', 'Varanasi'],
    anchorCity: 'Delhi',
    daysMin: 6,
    daysMax: 8,
    highlights: ['Khajuraho temple carvings', 'Ganga Aarti at Dashashwamedh Ghat', 'Sarnath Buddhist ruins', 'Boat ride at sunrise on Ganga'],
    bestMonths: ['October', 'November', 'December', 'January', 'February', 'March'],
    difficulty: 'easy',
    icon: '🕯️',
    coverEmoji: '🌅',
    popular: true,
  },

  // ── MULTI-REGION ─────────────────────────────────────────────────────────
  {
    id: 'india-grand-trail',
    name: 'India Grand Trail',
    tagline: 'North to South — the complete experience',
    region: 'north',
    vibes: ['heritage', 'cultural', 'nature', 'beach'],
    cities: ['Delhi', 'Agra', 'Jaipur', 'Mumbai', 'Goa', 'Kochi'],
    anchorCity: 'Delhi',
    daysMin: 16,
    daysMax: 21,
    highlights: ['Taj Mahal', 'Rajasthan palaces', 'Mumbai street life', 'Goa beaches', 'Kerala backwaters'],
    bestMonths: ['November', 'December', 'January', 'February'],
    difficulty: 'moderate',
    icon: '🇮🇳',
    coverEmoji: '✈️',
    popular: false,
  },
  {
    id: 'andaman-islands',
    name: 'Andaman Islands',
    tagline: 'Pristine coral reefs & tropical beaches',
    region: 'east',
    vibes: ['beach', 'adventure', 'nature', 'romantic'],
    cities: ['Port Blair', 'Havelock Island', 'Neil Island'],
    anchorCity: 'Port Blair',
    daysMin: 6,
    daysMax: 9,
    highlights: ['Radhanagar Beach sunset', 'Elephant Beach snorkelling', 'Cellular Jail tour', 'Glass-bottom boat rides'],
    bestMonths: ['November', 'December', 'January', 'February', 'March', 'April'],
    difficulty: 'easy',
    icon: '🐠',
    coverEmoji: '🏝️',
    popular: true,
  },
];

export default CIRCUITS;

// ── Helpers ──────────────────────────────────────────────────────────────────

export function getCircuitsByRegion(region: Region): Circuit[] {
  return CIRCUITS.filter(c => c.region === region);
}

export function getCircuitsByVibe(vibe: Vibe): Circuit[] {
  return CIRCUITS.filter(c => c.vibes.includes(vibe));
}

export function getPopularCircuits(): Circuit[] {
  return CIRCUITS.filter(c => c.popular);
}

export function getCircuitById(id: string): Circuit | undefined {
  return CIRCUITS.find(c => c.id === id);
}

export function searchCircuits(query: string): Circuit[] {
  const q = query.toLowerCase();
  return CIRCUITS.filter(c =>
    c.name.toLowerCase().includes(q) ||
    c.cities.some(city => city.toLowerCase().includes(q)) ||
    c.tagline.toLowerCase().includes(q) ||
    c.vibes.some(v => v.includes(q)) ||
    c.region.includes(q)
  );
}
