function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function exportPDF(content: string, destination: string): void {
  if (!content) return;
  const printWin = window.open('', '_blank');
  if (!printWin) return;
  printWin.document.write(`
    <!DOCTYPE html><html><head>
    <title>Yatra – ${escapeHtml(destination)} Itinerary</title>
    <style>
      body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1A0A00; line-height: 1.8; }
      h1 { color: #8B1A1A; font-size: 2rem; border-bottom: 3px solid #F0A500; padding-bottom: 10px; }
      pre { white-space: pre-wrap; font-family: Georgia, serif; font-size: 0.95rem; }
      .footer { margin-top: 40px; color: #888; font-size: 0.8rem; border-top: 1px solid #ddd; padding-top: 10px; }
      @media print { body { margin: 20px; } }
    </style></head><body>
    <h1>🪔 Yatra – ${escapeHtml(destination)} Itinerary</h1>
    <p style="color:#888;font-size:0.85rem;">Generated on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
    <pre>${escapeHtml(content)}</pre>
    <div class="footer">Generated by Yatra – Indian Travel Planner</div>
    <script>window.onload=()=>{window.print();}<\/script>
    </body></html>`);
  printWin.document.close();
}

export function shareItinerary(content: string, destination: string): void {
  if (!content) return;
  const shareText = `🪔 My ${destination} travel plan from Yatra:\n\n${content.slice(0, 500)}...\n\nPlan your trip at Yatra!`;
  if (navigator.share) {
    navigator.share({ title: `Yatra – ${destination} Itinerary`, text: shareText, url: window.location.href })
      .catch(() => copyToClipboard(shareText));
  } else {
    copyToClipboard(shareText);
  }
}

function copyToClipboard(text: string): void {
  navigator.clipboard.writeText(text).catch(() => {});
}
