import { marked, Renderer } from 'marked';

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// Custom renderer that escapes raw HTML blocks so inline HTML in
// AI-generated content cannot execute scripts in the print window.
const safeRenderer = new Renderer();
safeRenderer.html = ({ text }: { text: string }) => escapeHtml(text);

export function exportPDF(content: string, destination: string): void {
  if (!content) return;
  const printWin = window.open('', '_blank');
  if (!printWin) return;

  // Convert markdown → HTML so PDF renders formatted text, not raw symbols
  const htmlContent = marked.parse(content, { async: false, renderer: safeRenderer }) as string;

  printWin.document.write(`
    <!DOCTYPE html><html><head>
    <title>Yatra – ${escapeHtml(destination)} Itinerary</title>
    <style>
      body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1A0A00; line-height: 1.8; }
      h1 { color: #8B1A1A; font-size: 2rem; border-bottom: 3px solid #F0A500; padding-bottom: 10px; }
      h2 { color: #8B1A1A; font-size: 1.4rem; margin-top: 28px; border-bottom: 1px solid #F0D5B0; padding-bottom: 6px; }
      h3 { color: #5C3317; font-size: 1.1rem; margin-top: 16px; }
      a { color: #8B1A1A; }
      table { border-collapse: collapse; width: 100%; margin: 12px 0; }
      th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
      th { background: #FFF3E0; font-weight: bold; }
      ul, ol { padding-left: 20px; }
      hr { border: none; border-top: 1px solid #eee; margin: 20px 0; }
      .footer { margin-top: 40px; color: #888; font-size: 0.8rem; border-top: 1px solid #ddd; padding-top: 10px; }
      @media print { body { margin: 20px; } a { color: #8B1A1A; } }
    </style></head><body>
    <h1>🪔 Yatra – ${escapeHtml(destination)} Itinerary</h1>
    <p style="color:#888;font-size:0.85rem;">Generated on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
    ${htmlContent}
    <div class="footer">Generated by Yatra – Indian Travel Planner | AI-generated content, verify locally before travel.</div>
    <script>window.onload=()=>{window.print();}<\/script>
    </body></html>`);
  printWin.document.close();
}

export function shareItinerary(content: string, destination: string): void {
  if (!content) return;
  const shareText = `🪔 My ${destination} travel plan from Yatra:\n\n${content.slice(0, 500)}...\n\nPlan your trip at Yatra!`;
  if (navigator.share) {
    navigator.share({ title: `Yatra – ${destination} Itinerary`, text: shareText, url: window.location.href })
      .catch(() => copyToClipboard(shareText));
  } else {
    copyToClipboard(shareText);
  }
}

function copyToClipboard(text: string): void {
  navigator.clipboard.writeText(text).catch(() => {});
}
